// Generated by https://quicktype.io

export interface LoginBody {
  identifier: string;
  password: string;
}

export interface Login {
  jwt: string;
  user: User;
}

export interface User {
  id: number;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  createdAt: string;
  updatedAt: string;
  birthday_date: string;
}
