// Generated by https://quicktype.io

export interface OrderResponse {
  data: OrderDatum[];
  meta: Meta;
}

export interface OrderDatum {
  id: number;
  attributes: OrderAttributes;
}

export interface OrderAttributes {
  id?: number;
  completed: boolean;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  name: string;
  slug: string;
  shipping_method: string;
  products: Product[];
  users_permissions_user: UsersPermissionsUser;
  addresses: Addresses;
  phones: Phones;
  date: Date;
  shipping_price: number;
  shipping_code?: string;
  shipping_company?: string;
}

export interface Addresses {
  data: AddressesDatum[];
}

export interface AddressesDatum {
  id: number;
  attributes: FluffyAttributes;
}

export interface FluffyAttributes {
  province: string;
  postal_code: string;
  city: string;
  address: string;
  observations: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  primary: boolean;
  name: string;
}

export interface Phones {
  data: PhonesDatum[];
}

export interface PhonesDatum {
  id: number;
  attributes: TentacledAttributes;
}

export interface TentacledAttributes {
  name: string;
  area_code: string;
  number_phone: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  primary: boolean;
}

export interface Product {
  slug: string;
  quantity: number;
  id?: number;
}

export interface UsersPermissionsUser {
  data: Data;
}

export interface Data {
  id: number;
  attributes: DataAttributes;
}

export interface DataAttributes {
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  createdAt: string;
  updatedAt: string;
  birthday_date: string;
  name: string;
  lastName: string;
}

export interface Meta {
  pagination: Pagination;
}

export interface Pagination {
  page: number;
  pageSize: number;
  pageCount: number;
  total: number;
}
