// Generated by https://quicktype.io

export interface User {
  id: number;
  username: string;
  email: string;
  provider: string;
  confirmed: boolean;
  blocked: boolean;
  createdAt: string;
  updatedAt: string;
  birthday_date: string;
  image: Image;
  addresses: Address[];
  phones: Phone[];
  name: string;
  lastName: string;
  favorites: Favorites[];
}

export interface Address {
  id: number;
  province: string;
  postal_code: string;
  city: string;
  address: string;
  observations: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  primary: boolean;
  name: string;
}

export interface Image {
  id: number;
  name: string;
  alternativeText: null;
  caption: null;
  width: number;
  height: number;
  formats: Formats;
  hash: string;
  ext: string;
  mime: string;
  size: number;
  url: string;
  previewUrl: null;
  provider: string;
  provider_metadata: ProviderMetadata;
  createdAt: string;
  updatedAt: string;
}

export interface Formats {
  large: Large;
  small: Large;
  medium: Large;
  thumbnail: Large;
}

export interface Large {
  ext: string;
  url: string;
  hash: string;
  mime: string;
  name: string;
  path: null;
  size: number;
  width: number;
  height: number;
  provider_metadata: ProviderMetadata;
}

export interface ProviderMetadata {
  public_id: string;
  resource_type: string;
}

export interface Phone {
  id: number;
  name: string;
  area_code: string;
  number_phone: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  primary: boolean;
}

export interface Favorites {
  id: number;
  slug: string;
  createdAt: string;
  publishedAt: string;
  updatedAt: string;
}
