import { Request, Response } from "express";
import mercadopago from "mercadopago";
import { MP_ACCESS_TOKEN } from "../config";
import axios from "axios";

mercadopago.configure({
  access_token: `${MP_ACCESS_TOKEN}`,
});

// Generated by https://quicktype.io

interface Example {
  action: string;
  api_version: string;
  application_id: string;
  date_created: string;
  id: string;
  live_mode: string;
  type: string;
  user_id: number;
  data: Data;
}

export interface Data {
  id: string;
}

global.orderId = "";
global.jwt = "";
global.userId = "";

export const createOrder = async (req: Request, res: Response) => {
  const items = req.body.items;
  const order = req.body.order;
  const shipping_price = req.body.shipping_price;
  global.userId = req.body.userId;
  global.jwt = req.body.jwt;
  global.orderId = req.body.orderId;

  const result = await mercadopago.preferences.create({
    items: items,

    shipments: {
      cost: shipping_price,
      mode: "not_specified",
    },

    back_urls: {
      success: `https://delidrinks-ecommerce.vercel.app/resume/${order}`,
      failure: `https://delidrinks-ecommerce.vercel.app/resume/${order}`,
      //   pending: "https://7qrrtvzm-4200.brs.devtunnels.ms/",
    },
    auto_return: "approved",

    notification_url: "https://7qrrtvzm-3000.brs.devtunnels.ms/webhook",
  });

  res.send(result);
};

export const webhook = async (req: Request, res: Response) => {
  const payment: Example = req.body;

  console.log(payment);

  try {
    if (payment.type === "payment") {
      const orderId = global.orderId;
      const userId = global.userId;
      const jwt = global.jwt;

      const requestBody = {
        data: {
          completed: true,
          users_permissions_users: userId,
        },
      };

      const axiosInstance = axios.create({
        baseURL: "https://delidrinks-ecommerce-production.up.railway.app/api",
        headers: {
          Authorization: `Bearer ${jwt}`,
        },
      });

      const response = await axiosInstance.put(
        `/orders/${orderId}`,
        requestBody
      );
      console.log({ "Respuesta de axios": response });
      console.log("Salio todo bien pa");
      return res.sendStatus(200);
    }

    return res.status(404);
  } catch (error) {
    console.log(error);
    return res.status(500).json({ error });
  }
};
